config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    #path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('translation.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

translation/urls.py
from django.urls import path
from . import views

app_name = 'translation'

urlpatterns = [
    path('', views.TopView.as_view(), name='top'),
    path('translation/', views.save_transcription, name='save_transcription'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('mypage/<int:pk>/', views.MypageView.as_view(), name='mypage'),
    path('mypage_edit/<int:pk>/', views.MypageEditView.as_view(), name='mypage_edit'),
]

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field.label }}
                    {{ field }}
                    {{ field.errors }}
                    <br>
                {% endfor %}
                <button type="submit" class="btn btn-success btn-block">ログイン</button>
            </div>
        </div>
    </div>
</form>

{% endblock content %}

templates/accounts/mypage.html
{% extends 'base.html' %}

{% block content %}
{% include 'header.html' %}

{% if messages %}
<div class="messages alert alert-primary" role="alert">
    {% for message in messages %}
        {{ message }}
    {% endfor %}
</div>
{% endif %}
<div class="container my-5">
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'translation:save_transcription' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">マイページ</li>
        </ol>
    </nav>
    <h2>{{ user }}さんのページ</h2>
    <hr>
    <div class="container my-3">
        <div class="col-md-12 mt-5">
            <ul class="list-group">
                <li class="list-group-item">名前：{{ user.username }}</li>
                <li class="list-group-item">メールアドレス：{{ user.email }}</li>
            </ul>
            <br>
            <a class="btn btn-secondary mb-3" href="{% url 'users:mypage_edit' user.pk %}" role="button">編集する</a>
        </div>
    </div>
    <hr>
    <h4>保存した翻訳リスト</h4>
    {% for text in translated %}
    <ul class="list-group list-group-horizontal">
        
        <li class="list-group-item col-md-6">{{ text.text_ja }}</li>
        <li class="list-group-item col-md-6">{{ text.text_en }}</li>
        
    </ul>
    {% endfor %}
{% endblock content %}

templates/accounts/mypage_edit.html
{% extends 'base.html' %}

{% block content %}
{% include 'header.html' %}

<div class="container mt-5">
    <div class="row">
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'users:mypage' user.pk %}">マイページ</a></li>
                <li class="breadcrumb-item active" aria-current="page">マイページ編集</li>
            </ol>
        </nav>
        <h2>マイページ編集</h2>
        <hr>
        <form class="row g-3" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="fieldWrapper col-md-12">
                {{ form.username.label_tag }}
                {{ form.username}}
            </div>
            <div class="fieldWrapper col-md-12">
                {{ form.email.label_tag }}
                {{ form.email }}
            </div>
            <div class="col-12">
            <input type="submit" value="更新" class="btn btn-secondary">
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field.label }}
                    {{ field }}
                    {{ field.errors }}
                    <br>
                {% endfor %}
                <button type="submit" class="btn btn-success btn-block">新規登録</button>
            </div>
        </div>
    </div>
</form>

{% endblock content %}