config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    #path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('translation.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

translation/urls.py
from django.urls import path
from . import views

app_name = 'translation'

urlpatterns = [
    path('', views.TopView.as_view(), name='top'),
    path('translation/', views.save_transcription, name='save_transcription'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('mypage/<int:pk>/', views.MypageView.as_view(), name='mypage'),
    path('mypage_edit/<int:pk>/', views.MypageEditView.as_view(), name='mypage_edit'),
]

templates/base.html
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Translation</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
    <body> 
        {% block content %}
        {% endblock content %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

templates/header.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'translation:save_transcription' %}">Home</a>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ user }}さん</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'users:mypage' user.pk %}">マイページ</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">ログアウト</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/top.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="text-center mt-5">
        <h1>TOP PAGE</h1>
        <p class="lead">A complete project boilerplate built with Bootstrap</p>
    </div>
</div>
<hr>
<div class="text-center mt-5">
    <a href="{% url 'users:login' %}" class="btn btn-primary">ログイン</a>
    <a href="{% url 'users:signup' %}" class="btn btn-primary">新規登録</a>
</div>
{% endblock content %}